import { NextRequest, NextResponse } from 'next/server';

const QUESTION_POOLS: Record<string, string[]> = {
  'Software Engineer': [
    "Explain the concept of polymorphism in object-oriented programming.",
    "What are design patterns and which ones have you used?",
    "How do you approach debugging complex issues in production?",
    "Compare SQL and NoSQL databases and when to use each.",
    "What’s the difference between threads and processes?",
    "How do you implement authentication and authorization in a web app?",
    "What are RESTful APIs and how do you design them?",
    "Describe your experience with version control systems like Git.",
    "What’s the purpose of CI/CD and how have you used it?",
    "How do you ensure code is scalable and maintainable?",
    "Explain the SOLID principles in object-oriented design.",
    "What’s your approach to writing unit tests?",
    "How would you optimize the performance of a web application?",
    "What is a memory leak and how do you prevent it?",
    "What tools do you use for performance monitoring?",
    "Explain the MVC architecture.",
    "Describe a situation where you handled technical debt.",
    "How do you manage dependencies in a large project?",
    "What is the difference between synchronous and asynchronous programming?",
    "What is the purpose of using Docker or containers?",
    "How do you implement caching and what strategies do you use?",
    "Describe your approach to peer code reviews.",
    "What’s your strategy for learning new programming languages?",
    "How do you handle race conditions in concurrent programming?",
    "What is your process for designing system architecture?"
  ],
  'Product Manager': [
    "How do you prioritize product features?",
    "Describe a time you managed a stakeholder disagreement.",
    "What is an MVP and why is it important?",
    "How do you perform a competitive analysis?",
    "Explain how you use data to inform decisions.",
    "How do you handle scope creep in a product roadmap?",
    "What KPIs do you track to measure product success?",
    "Describe your process for writing user stories.",
    "How do you decide between user needs and business goals?",
    "What tools do you use for product management?",
    "Explain your experience with Agile methodologies.",
    "How do you communicate with engineering teams?",
    "What’s your process for launching a new feature?",
    "Describe a product you’ve taken from idea to launch.",
    "How do you collect and act on customer feedback?",
    "How do you handle a failed product feature?",
    "What is the difference between product vision and product strategy?",
    "How do you define a product’s value proposition?",
    "What frameworks do you use for prioritization?",
    "Describe how you lead cross-functional teams.",
    "How do you validate a product hypothesis?",
    "What is your experience working with UX/UI designers?",
    "How do you make decisions when data is limited?",
    "How do you identify market opportunities?",
    "What is your approach to A/B testing?"
  ],
  'Data Analyst': [
    "What’s the difference between inner and outer joins?",
    "Explain how you clean a messy dataset.",
    "Describe a time you uncovered a key insight with data.",
    "What is the difference between correlation and causation?",
    "How do you handle missing values in a dataset?",
    "What tools do you use for data visualization?",
    "What’s the role of SQL in data analysis?",
    "Explain the concept of data normalization.",
    "How do you choose between mean, median, and mode?",
    "Describe your experience with Excel or Google Sheets.",
    "What’s your process for building a dashboard?",
    "What is a p-value and why is it important?",
    "How do you test a hypothesis using data?",
    "Describe your workflow for a typical data analysis project.",
    "What’s the difference between structured and unstructured data?",
    "How do you ensure data quality and integrity?",
    "Explain your experience with Python or R for analysis.",
    "How do you tell a story using data?",
    "What challenges have you faced with large datasets?",
    "What statistical techniques do you use frequently?",
    "How do you manage and document your analysis process?",
    "Explain ETL and your role in the process.",
    "What’s your experience with BI tools like Tableau or Power BI?",
    "How do you deal with outliers in a dataset?",
    "How do you measure the success of your analysis?"
  ],
  'UI/UX Designer': [
    "What’s your process for user research?",
    "Describe a time you improved usability.",
    "What tools do you use for wireframing and prototyping?",
    "How do you test your design with real users?",
    "Explain the difference between UX and UI.",
    "What design systems have you used before?",
    "How do you handle conflicting design feedback?",
    "How do you approach mobile-first design?",
    "What’s your experience with accessibility standards?",
    "How do you use personas in your design process?",
    "Describe a time you collaborated closely with developers.",
    "How do you measure the success of your design?",
    "How do you stay updated on design trends?",
    "What are your favorite UX metrics?",
    "How do you balance aesthetics and functionality?",
    "What is your approach to responsive design?",
    "How do you document your design decisions?",
    "What’s your process for creating a design brief?",
    "How do you handle deadlines on complex design tasks?",
    "What are some common UI mistakes you try to avoid?",
    "Describe a design challenge you overcame.",
    "How do you ensure consistency across a product?",
    "What’s your experience with Figma/Sketch/Adobe XD?",
    "What’s your strategy for conducting usability tests?",
    "What’s your design thinking approach?"
  ],
    'Marketing Specialist': [
    "How do you measure the success of a marketing campaign?",
    "What strategies do you use for lead generation?",
    "Explain your experience with SEO and SEM.",
    "How do you define a target audience?",
    "Describe a time when a campaign didn’t perform well — what did you learn?",
    "What tools do you use for email marketing?",
    "How do you approach content marketing?",
    "Explain the difference between inbound and outbound marketing.",
    "How do you work with sales teams to align marketing efforts?",
    "What’s your experience with Google Analytics?",
    "How do you stay updated with marketing trends?",
    "What’s your strategy for launching a new product?",
    "How do you use data to make marketing decisions?",
    "Describe a successful social media campaign you led.",
    "What KPIs do you track regularly?",
    "What is A/B testing and how do you use it?",
    "How do you manage a marketing budget?",
    "Describe a multi-channel marketing campaign you’ve executed.",
    "How do you segment audiences for campaigns?",
    "How do you ensure brand consistency across channels?",
    "What’s your experience with paid ads (Google/Facebook/etc.)?",
    "How do you generate ideas for creative marketing content?",
    "What role does storytelling play in marketing?",
    "How do you approach influencer marketing?",
    "What challenges have you faced in digital marketing and how did you overcome them?"
  ],
  'Other': [
    "Describe a challenging situation and how you solved it.",
    "What’s your greatest strength in a team setting?",
    "How do you handle tight deadlines?",
    "Explain how you adapt to a new environment.",
    "What motivates you to do your best work?",
    "Describe a time you had to learn something quickly.",
    "How do you handle failure or setbacks?",
    "What do you consider your biggest professional achievement?",
    "How do you approach problem-solving in general?",
    "Describe a time you took initiative.",
    "How do you communicate complex ideas to non-experts?",
    "What is your strategy for setting goals and meeting them?",
    "How do you handle feedback and criticism?",
    "What qualities do you think a good leader should have?",
    "How do you manage stress during busy periods?",
    "Describe a time you worked outside your job description.",
    "How do you balance quality and speed in your work?",
    "What does professional growth mean to you?",
    "How do you make decisions when there’s uncertainty?",
    "What’s your approach to teamwork and collaboration?",
    "Describe how you manage multiple priorities.",
    "How do you prepare for an important presentation or meeting?",
    "What do you do when you disagree with your manager?",
    "How do you ensure continuous learning in your career?",
    "What values do you bring to a workplace?"
  ]
};

function getRandomQuestions(role: string, count = 5): string[] {
  const pool = QUESTION_POOLS[role] || QUESTION_POOLS['Other'];
  const shuffled = pool.sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

export async function POST(req: NextRequest) {
  const { role } = await req.json();

  const questions = getRandomQuestions(role);

  return NextResponse.json({ questions });
}
