const feedbackTemplates = [
  "Great structure and clarity! Try adding specific examples.",
  "Good pace and tone. You can improve technical depth.",
  "Your answer covered key points, but lacked personal impact.",
  "Consider using STAR (Situation-Task-Action-Result) structure.",
  "Try avoiding filler words like 'um' or 'like'.",
  "Impressive content! A bit more enthusiasm would help.",
  "You spoke confidently. Add more measurable achievements.",
  "Focus more on how *you* made the impact.",
  "Solid answer. Could be more concise.",
  "Try elaborating more on the outcome.",
  "Good problem-solving approach. Add metrics if possible.",
  "Nice explanation! A bit more technical depth will improve it.",
  "Your answer was structured well. Add follow-up details.",
  "Impressive answer. Consider backing it with a project example.",
  "Avoid going off-topic; keep your answer focused.",
  "Great eye contact and tone (if it were video)!",
  "Mention challenges you overcame — it adds credibility.",
  "You sounded confident. Add context before diving in.",
  "Use numbers (like 'increased efficiency by 20%') for impact.",
  "Start with a brief summary before diving deep.",
  "You communicated clearly. Add more reflection.",
  "The example is strong. Connect it more directly to the role.",
  "Good start. Structure it as problem → solution → result.",
  "A bit too short. Try elaborating with details.",
  "Try using more action verbs: led, built, resolved.",
  "Excellent technical explanation. Try simplifying jargon.",
  "Avoid repeating the question in the beginning.",
  "You handled ambiguity well. Clarify your assumptions too.",
  "Speak more slowly to show confidence.",
  "Try to answer in under 2 minutes — it's a good range.",
  "Good story! Tie it back to the job role more.",
  "Add your learnings at the end to leave a mark.",
  "Use pauses to let your points sink in.",
  "Very clear answer. Could use a stronger conclusion.",
  "Good behavioral response. Make it role-specific.",
  "You demonstrated teamwork well. Now add personal value.",
  "Don’t be afraid to show personality and passion.",
  "Give context early to avoid confusion.",
  "Clarify acronyms — assume the interviewer doesn't know them.",
  "Strong technical depth. Simplify for non-tech interviewers.",
  "Great explanation! Just avoid going off on tangents.",
  "Mention your role even in team projects.",
  "Use real challenges instead of generic ones.",
  "Tie each experience to a skill the role demands.",
  "Avoid generic phrases like 'I’m a quick learner'.",
  "Very fluent — now focus on being more direct.",
  "Impressive example! Summarize key results at the end.",
  "Engaging story. Highlight your initiative more.",
  "Focus more on outcomes, less on the process.",
  "Good example of leadership. Be more specific in actions.",
  "Make sure you fully answer the *why* of the question.",
];

export function getRandomFeedback(): string {
  const index = Math.floor(Math.random() * feedbackTemplates.length);
  return feedbackTemplates[index];
}
